################################################################
##  AmazonBuyBot
##  2022 Pixel Wide Studio
##  Author: Jeffrey Frederick
################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *
import sys

class MainWindow(QMainWindow):

    def __init__(self):
        super(MainWindow, self).__init__()
        self.initGUI()

    def initGUI(self):
        # Main Form
        self.setObjectName("frmMain")
        self.setWindowTitle("AmazonBuyBot [Idle]")
        self.resize(390, 388)
        self.tabMain = QTabWidget(self)
        self.tabMain.setObjectName("tabMain")
        self.tabMain.setGeometry(QRect(10, 10, 370, 320))
        self.tabMain.setCurrentIndex(0)
        # Buttons
        self.btnStart = QPushButton(self)
        self.btnStart.setObjectName("btnStart")
        self.btnStart.setEnabled(False)
        self.btnStart.setGeometry(QRect(280, 340, 100, 40))
        self.btnStart.setText(QCoreApplication.translate("frmMain", "Start", None))
        self.btnStop = QPushButton(self)
        self.btnStop.setObjectName("btnStop")
        self.btnStop.setEnabled(False)
        self.btnStop.setGeometry(QRect(180, 340, 100, 40))
        self.btnStop.setText(QCoreApplication.translate("frmMain", "Stop", None))
        self.btnExit = QPushButton(self)
        self.btnExit.setObjectName("btnExit")
        self.btnExit.setGeometry(QRect(10, 340, 100, 40))
        self.btnExit.setText(QCoreApplication.translate("frmMain", "Exit", None))

        # Billing Tab
        self.tabBilling = QWidget(self)
        self.tabBilling.setObjectName("tabBilling")
        self.tabMain.addTab(self.tabBilling, "")
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabBilling), QCoreApplication.translate("frmMain", "Billing", None))
        # Labels
        self.lblName = QLabel(self.tabBilling)
        self.lblName.setObjectName("lblName")
        self.lblName.setGeometry(QRect(10, 10, 64, 26))
        self.lblName.setText(QCoreApplication.translate("frmMain", "Name:", None))
        self.lblNumber = QLabel(self.tabBilling)
        self.lblNumber.setObjectName("lblNumber")
        self.lblNumber.setGeometry(QRect(10, 50, 64, 26))
        self.lblNumber.setText(QCoreApplication.translate("frmMain", "Number:", None))
        self.lblEXP = QLabel(self.tabBilling)
        self.lblEXP.setObjectName("lblEXP")
        self.lblEXP.setGeometry(QRect(10, 90, 64, 26))
        self.lblEXP.setText(QCoreApplication.translate("frmMain", "EXP:", None))
        self.lblCCV = QLabel(self.tabBilling)
        self.lblCCV.setObjectName("lblCCV")
        self.lblCCV.setGeometry(QRect(160, 90, 64, 26))
        self.lblCCV.setText(QCoreApplication.translate("frmMain", "CCV:", None))
        self.lblAddress = QLabel(self.tabBilling)
        self.lblAddress.setObjectName("lblAddress")
        self.lblAddress.setGeometry(QRect(10, 130, 64, 26))
        self.lblAddress.setText(QCoreApplication.translate("frmMain", "Address:", None))
        self.lblAddress_2 = QLabel(self.tabBilling)
        self.lblAddress_2.setObjectName("lblAddress_2")
        self.lblAddress_2.setGeometry(QRect(10, 170, 64, 26))
        self.lblAddress_2.setText(QCoreApplication.translate("frmMain", "Address 2:", None))
        self.lblCity = QLabel(self.tabBilling)
        self.lblCity.setObjectName("lblCity")
        self.lblCity.setGeometry(QRect(10, 210, 64, 26))
        self.lblCity.setText(QCoreApplication.translate("frmMain", "City:", None))
        self.lblState = QLabel(self.tabBilling)
        self.lblState.setObjectName("lblState")
        self.lblState.setGeometry(QRect(250, 210, 64, 28))
        self.lblState.setText(QCoreApplication.translate("frmMain", "State:", None))
        self.lblZip = QLabel(self.tabBilling)
        self.lblZip.setObjectName("lblZip")
        self.lblZip.setGeometry(QRect(260, 90, 64, 28))
        self.lblZip.setText(QCoreApplication.translate("frmMain", "Zip:", None))
        # TextBoxes
        self.txtName = QPlainTextEdit(self.tabBilling)
        self.txtName.setObjectName("txtName")
        self.txtName.setGeometry(QRect(80, 10, 270, 26))
        self.txtName.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txtName.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txtNumber_1 = QPlainTextEdit(self.tabBilling)
        self.txtNumber_1.setObjectName("txtNumber_1")
        self.txtNumber_1.setGeometry(QRect(80, 50, 60, 26))
        self.txtNumber_1.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txtNumber_1.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txtNumber_2 = QPlainTextEdit(self.tabBilling)
        self.txtNumber_2.setObjectName("txtNumber_2")
        self.txtNumber_2.setGeometry(QRect(150, 50, 60, 26))
        self.txtNumber_2.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txtNumber_2.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txtNumber_3 = QPlainTextEdit(self.tabBilling)
        self.txtNumber_3.setObjectName("txtNumber_3")
        self.txtNumber_3.setGeometry(QRect(220, 50, 60, 26))
        self.txtNumber_3.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txtNumber_3.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txtNumber_4 = QPlainTextEdit(self.tabBilling)
        self.txtNumber_4.setObjectName("txtNumber_4")
        self.txtNumber_4.setGeometry(QRect(290, 50, 60, 26))
        self.txtNumber_4.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txtNumber_4.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txtEXP = QPlainTextEdit(self.tabBilling)
        self.txtEXP.setObjectName("txtEXP")
        self.txtEXP.setGeometry(QRect(50, 90, 100, 26))
        self.txtEXP.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txtEXP.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txtEXP.setPlaceholderText(QCoreApplication.translate("frmMain", "XX/XX/XXXX", None))
        self.txtCCV = QPlainTextEdit(self.tabBilling)
        self.txtCCV.setObjectName("txtCCV")
        self.txtCCV.setGeometry(QRect(200, 90, 48, 26))
        self.txtCCV.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txtCCV.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txtZip = QPlainTextEdit(self.tabBilling)
        self.txtZip.setObjectName("txtZip")
        self.txtZip.setEnabled(False)
        self.txtZip.setGeometry(QRect(290, 90, 60, 26))
        self.txtZip.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txtZip.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txtAddress = QPlainTextEdit(self.tabBilling)
        self.txtAddress.setObjectName("txt_Address")
        self.txtAddress.setEnabled(False)
        self.txtAddress.setGeometry(QRect(80, 130, 270, 26))
        self.txtAddress.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txtAddress.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txtAddress_2 = QPlainTextEdit(self.tabBilling)
        self.txtAddress_2.setObjectName("txtAddress_2")
        self.txtAddress_2.setEnabled(False)
        self.txtAddress_2.setGeometry(QRect(80, 170, 270, 26))
        self.txtAddress_2.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txtAddress_2.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txtCity = QPlainTextEdit(self.tabBilling)
        self.txtCity.setObjectName("txtCity")
        self.txtCity.setEnabled(False)
        self.txtCity.setGeometry(QRect(50, 210, 180, 26))
        self.txtCity.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txtCity.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        # ComboBoxes
        self.cboState = QComboBox(self.tabBilling)
        self.cboState.setObjectName("cboState")
        self.cboState.setEnabled(False)
        self.cboState.setGeometry(QRect(290, 210, 68, 31))
        # CheckBoxes
        self.chkBillingSame = QCheckBox(self.tabBilling)
        self.chkBillingSame.setObjectName("chkBillingSame")
        self.chkBillingSame.setGeometry(QRect(130, 260, 231, 20))
        self.chkBillingSame.setChecked(True)
        self.chkBillingSame.setText(QCoreApplication.translate("frmMain", "Billing Address Same As Shipping", None))

        # Login Tab
        self.tabLogin = QWidget(self)
        self.tabLogin.setObjectName("tabLogin")
        self.tabMain.addTab(self.tabLogin, "")
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabLogin), QCoreApplication.translate("frmMain", "Login", None))
        # Labels
        self.lblUsername = QLabel(self.tabLogin)
        self.lblUsername.setObjectName("lblUsername")
        self.lblUsername.setGeometry(QRect(10, 10, 64, 26))
        self.lblUsername.setText(QCoreApplication.translate("frmMain", "Username:", None))
        self.lblPassword = QLabel(self.tabLogin)
        self.lblPassword.setObjectName("lblPassword")
        self.lblPassword.setGeometry(QRect(10, 50, 64, 26))
        self.lblPassword.setText(QCoreApplication.translate("frmMain", "Password:", None))
        # TextBoxes
        self.txtUsername = QPlainTextEdit(self.tabLogin)
        self.txtUsername.setObjectName("txtUsername")
        self.txtUsername.setGeometry(QRect(80, 10, 270, 26))
        self.txtUsername.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txtUsername.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txtPassword = QPlainTextEdit(self.tabLogin)
        self.txtPassword.setObjectName("txtPassword")
        self.txtPassword.setGeometry(QRect(80, 50, 270, 26))
        self.txtPassword.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.txtPassword.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        # Checkboxes
        self.chkShowPassword = QCheckBox(self.tabLogin)
        self.chkShowPassword.setObjectName("chkShowPassword")
        self.chkShowPassword.setGeometry(QRect(230, 90, 121, 20))
        self.chkShowPassword.setText(QCoreApplication.translate("frmMain", "Show Password", None))

        # Cookies Tab
        self.tabCookies = QWidget(self)
        self.tabCookies.setObjectName("tabCookies")
        self.tabMain.addTab(self.tabCookies, "")
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabCookies), QCoreApplication.translate("frmMain", "Cookies", None))
        # Labels
        self.lblCSV = QLabel(self.tabCookies)
        self.lblCSV.setObjectName("lblCSV")
        self.lblCSV.setGeometry(QRect(10, 10, 90, 26))
        self.lblCSV.setText(QCoreApplication.translate("frmMain", "CSV File(s):", None))
        # Lists
        self.lstCSV = QListView(self.tabCookies)
        self.lstCSV.setObjectName("lstCSV")
        self.lstCSV.setGeometry(QRect(10, 40, 344, 200))
        # Buttons
        self.btnLoadCSV = QPushButton(self.tabCookies)
        self.btnLoadCSV.setObjectName("btnLoadCSV")
        self.btnLoadCSV.setGeometry(QRect(160, 250, 100, 40))
        self.btnLoadCSV.setText(QCoreApplication.translate("frmMain", "Load CSV...", None))
        self.btnRemoveCSV = QPushButton(self.tabCookies)
        self.btnRemoveCSV.setObjectName("btnRemoveCSV")
        self.btnRemoveCSV.setEnabled(False)
        self.btnRemoveCSV.setGeometry(QRect(260, 250, 100, 40))
        self.btnRemoveCSV.setText(QCoreApplication.translate("frmMain", "Remove", None))

        # Products Tab
        self.tabProducts = QWidget(self)
        self.tabProducts.setObjectName("tabProducts")
        self.tabMain.addTab(self.tabProducts, "")
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabProducts), QCoreApplication.translate("frmMain", "Products", None))
        # Labels
        self.lblProductID = QLabel(self.tabProducts)
        self.lblProductID.setObjectName("lblProductID")
        self.lblProductID.setGeometry(QRect(10, 10, 90, 26))
        self.lblProductID.setText(QCoreApplication.translate("frmMain", "Product ID(s):", None))
        # Lists
        self.lstProductID = QListView(self.tabProducts)
        self.lstProductID.setObjectName("lstProductID")
        self.lstProductID.setGeometry(QRect(10, 40, 344, 200))
        # Buttons
        self.btnAddProductID = QPushButton(self.tabProducts)
        self.btnAddProductID.setObjectName("btnAddProductID")
        self.btnAddProductID.setGeometry(QRect(160, 250, 100, 40))
        self.btnAddProductID.setText(QCoreApplication.translate("frmMain", "Add", None))
        self.btnRemoveProductID = QPushButton(self.tabProducts)
        self.btnRemoveProductID.setObjectName("btnRemoveProductID")
        self.btnRemoveProductID.setEnabled(False)
        self.btnRemoveProductID.setGeometry(QRect(260, 250, 100, 40))
        self.btnRemoveProductID.setText(QCoreApplication.translate("frmMain", "Remove", None))

        # Config Tab
        self.tabConfig = QWidget(self)
        self.tabConfig.setObjectName("tabConfig")
        self.tabMain.addTab(self.tabConfig, "")
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabConfig), QCoreApplication.translate("frmMain", "Config", None))
        # Checkboxes
        self.chkEnableLogging = QCheckBox(self.tabConfig)
        self.chkEnableLogging.setObjectName("chkEnableLogging")
        self.chkEnableLogging.setGeometry(QRect(10, 10, 121, 26))
        self.chkEnableLogging.setChecked(True)
        self.chkEnableLogging.setText(QCoreApplication.translate("frmMain", "Enable Logging", None))

        self.show()

def main():
    app = QApplication(sys.argv)
    win = MainWindow()
    app.exec_()

if __name__ == '__main__':
    main()